language: python
dist: xenial
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev --deploy --python `which python`
- pip install -e git+https://git@github.com/uc-cdis/wool.git#egg=wool
script:
- if [[ $PR_NUMBER != false ]]; then GITHUB_TOKEN=$GH_TOKEN wool; fi
before_deploy:
- sed -i.bak "s/=get_version()/='$TRAVIS_TAG'/g" setup.py
- cat setup.py
- if [ $(python setup.py --version) == '0.0.0' ]; then travis_terminate 1; fi
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: zvUtKctGWJ2R7sdRPTcIvz8C1aYuwV5XoSJpDwLtkTU412JCTSo/5Uh9eIq5N/Oj3+BGCjgXzWN8l4spG5feCqzvcmBezUFsvnnElYaxrMWy5EY1SsLsaHq5arhDE5nCx9Trk2jg2KayWVdGSu3iDobZETX/5ozz/OPWSJQsNHzbeHY3SQOU4nDzlXHqxSVEg27Fl3KQA8v2rPk6hKmIeK5T+mMKzQ2P8HxKh6HQ+fgfy7T4bcZev8ojYsqSGxIgKMESa2/FX4tHdwQZkVd4KVM4QHv2szxuJovGzbkDSFsQoAQjWi75AIWtgrb6kCp6i+4afOB6l7Nxbqbze91Sy3pkLMsrLohIMP5oeX15Mn6W8RnwVj6LSmxFLFbfE0crZEI626uD5wwCaQ+rZwBSIPNYZYyVsZroWkcbIea8qpL7T7vbGYXnWS9GW5yfhjRirEqbI6E1Yw1+K5E83zsoMqMD977KVICMUyrF+iEe/hXA6gAea/xsI+0MNmiaup2Jdhq1yD0KyMNOE2Jk+IDY7zZII0qy+N7i56DphXKil/V9xNU7B0zUWGqkaGMqK42ky+U90vP4dW6syX9B1RQknqwhcjrQMPlKsx61pqIkZFsccZpcpx1hkCzusRvHeihGCA3h+G3brHXU9Lbvc0MAcVu4ES7MidkFS5DYutFr6Sw=
after_deploy:
- pip install gen3git
- gen3git release
env:
  matrix:
  - REPOSITORY="uc-cdis/gen3users" PR_NUMBER="$TRAVIS_PULL_REQUEST"
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1
  - secure: Y8lvxm4A28mVuYyigHNpW4r4MI4NsrOr2agprV/Qkjuk0xEqLWSIcVly1Gi2foVLb+ahNl+anmBjMXiuBQLSnA+ZX3/AQvkCkCzUOM6U0HOtbl9mpPg7EtxAiXwmCLu4/aHLYa2rx+7FYCz+qry2SV3wDGWYoBP1ITdAgcpztAYx69V8BBqDseI8liFxJt9ZvgZQdyhpVBfIbnpyN8n7efw/NFtUOmsj9teXlCibPjSKXzAITreibQJR6TPy/ksgDSOhVn46jfCxa1NQG9uElM2Ehjv3+V4PYmEyLmyWdb3zWvLDt8CEw1SuEMX5PT8aE1Vi/WVVoHKMWTcaFTQLVeDvgchtbYxhp0MgHMOt0t00B/O/WwpKsE4hSFAcK9SAAHEIJ80IpRkHU4G/7BjZIUaKlgU/XBmTa+cn+y19q78hL8RyXRWeslAk9/t5pfpLeuzvdx/oYl0vzdmSM7XNwz87YOg+g9+CkJRZD199QVhBKgioE77j8FSQVz6jfxm/8khjEPT0r46IxveCej4kqLQaZzjymVo3jteKEHZELF3u3kpzC4GlbjKvc7k3SGoHfW+SiANFVPAncefBM7VvlBHk15OF4YfPX1CVlu96tuWFAVvL64OOdvf9SCxm40zlsc3hYTdRXZFGdbfkniab036bu6FvYTNkbLVEiyzVKwE=
