language: python
dist: xenial
python:
- 3.9
install:
- pip install poetry
- poetry install -vv --no-interaction
script:
- poetry run pytest -vv ./tests
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -n -vv
  skip_cleanup: true
  on:
    repo: uc-cdis/gen3users
    tags: true
after_deploy:
- pip install gen3git
- gen3git release
env:
  global:
  - secure: "e7drsRlnfcDkf/g0WQrnFNk9M4I+wtDV3OkC5CqkmU27XBKr1rMTfEqHjcd13IqY5+xTh3lu7c3LX93A2p0DFZgpVYwHXjhx8q91r9+jLgybbQgiaiO9Lbz2asPum6sHn+g8GeP6GjSqCvUEqAiF3DoIFjz4+q72Pieq724r3Vl/oMGRHlD6lRRiop0BI760gavOgg7oPTudmeO7GKVObGsRW/J8xESa2D9fd5h09KETGcm3SLz6PmzM66ploI9NnvNT3jHryKoZW5H8S8i7cRkwRy7ig7+D216qo1YfBEEpXOLTJ+zEaj1p5UiS0SFmSjNRdiiW+orWwcbyDhV31WOmnNbE/Jd6uuYLBZ8htHOtX5ANvZQy5Hcz19qBW38C+BHFwqTFH+FxqNAOFqCRMFClzmdpXTsgTK5xLfb0o9+oyVA6FPmlfnb6juiNkaF0GtyZkFKEb7Qzh8HDVnLe29CrAHcZ3ewV0iMWXpQCeRiQ8GLwqN173aK/mBeR4el6CD7efdoY1cEFo5Ql2bTFPJgVMBLmUevuJt7k01xJHdB4xT1moJlEdT/Jqp/sjRayY8I0BvjmEp8k7OsBCu9VzqzU2Jehg/C5d2XQNHUFFd9Bfx5bgVZuQnI8RW9wpOwUYr7bltsmLKnSWp0PTZouZuWUgpeBpp1S13ejqKBWXyw="
  - secure: "cWS9kxcmfwgb8Ibld/4PXyWCU+hyCj9thh8LwJbALuJHJX83BE+e1AMTPngcIm8n7nVHOZjQFRHBA2qiFgyA7UEd9Dd9xEkbSpoWcnnBXOnlued6Nw+1Oa9yDHOq2uBXn4XBpoYajyLRJNTTeJh8JPnp4rgx4UG8vOinpx0f8TKxdhJ0c3lvkdM3RfbLZRRt9ISL9FdBr2Svxvuvbnfsv6N1yJQrY8Ya8qBaottfNlXMR4wuaHuYmC5j5Cq3wy5sYGecru8piJhgHzyD+Le/tmV+bqRBwicFczJgrGnXxMdP+oiNxqt81ikIolKoA7vqSnZ5wvFzI04FfDaFVgOA1eG7g+faT8fFNpRTBRDWoKFH4gVbwbu9ox1xJ7nYUYoTKrI8ogAsAUAgqbztOFVGYKgGHK1xM+itaX9e3wlvGtDDRS8yAo2bU0utdgRWpNJ5lYLJieLo3hvay5CQQJWNC7nAjJ2GhNzYbau3AcTu5itXqrLt5rR4DHvdBTn8LOlrUKddosYjMpckgV6Cn7pPBopy3rSMTlOOPeeE1KZJ9Bi5dorHaYehuSeTZEI4ue8xZX0FuhheErGYYIZAZGtQWj8G8b7FZiQTxOWV5frOPSo4EGlqzQawCXvK3EqnyFqezfa5KdI86pVVAqUtDVke61xnd7lsrs5Ku4vmRW+2ieI="
