name: CI

on:
  # run on pushed commits to master and on new commits on pull requests
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

env:
  USER_YAML_GITHUB_PAT: ${{secrets.USER_YAML_GITHUB_PAT}}

jobs:
  Security:
    name: Security Pipeline
    uses: uc-cdis/.github/.github/workflows/securitypipeline.yaml@master
    secrets: inherit
  UnitTest:
    name: Python Unit Test
    uses: uc-cdis/.github/.github/workflows/python_unit_test.yaml@master
    with:
        python-version: '3.9'
